name: Build resume file and deploy to github pages

on:
  push:
    branches: master
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE
      - preview/*

  workflow_dispatch:

jobs:
  build:
    name: Compile LaTeX document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: resume.pdf
